/*
 * Markup shared by the two generators.
 *
 * The drug bag / CD tracker (index.html) and the drug matrix (matrix.html) are
 * separate pages with separate storage, but they ask for a medication in the
 * same way and carry the same company details, save/load controls and small
 * print. Rather than keep two copies of that markup in step by hand, each page
 * drops a <div data-part="..."> where a shared block belongs and this fills it.
 *
 * Wording that differs between the two is set at runtime by app.js, so what is
 * here is deliberately neutral.
 */
(function (global) {
  "use strict";

  var PARTS = {
    company: [
      "<div class=\"card\">",
      "  <h2>Company details</h2>",
      "  <p class=\"hint\">Who the document belongs to. Printed at the top of everything this tool",
      "    produces, and in the &ldquo;if found&rdquo; notice on a bag label. Save them once and load",
      "    them into any document &mdash; the logo comes too.</p>",
      "  <div class=\"actions company-actions\">",
      "    <button type=\"button\" class=\"btn ghost small\" id=\"companyExportBtn\">Export company details</button>",
      "    <button type=\"button\" class=\"btn ghost small\" id=\"companyImportBtn\">Import company details</button>",
      "    <input type=\"file\" id=\"companyFile\" accept=\"application/json,.json\" hidden>",
      "  </div>",
      "  <p class=\"notice\" id=\"companyResult\" hidden></p>",
      "  <div class=\"grid\">",
      "    <label class=\"field\">",
      "      <span>Company name <b>*</b></span>",
      "      <input type=\"text\" id=\"companyName\" placeholder=\"e.g. Northern Event Medical Ltd\" autocomplete=\"organization\">",
      "    </label>",
      "    <label class=\"field\">",
      "      <span>Contact number <b>*</b></span>",
      "      <input type=\"tel\" id=\"companyPhone\" placeholder=\"e.g. 01234 567890\" autocomplete=\"tel\">",
      "    </label>",
      "    <label class=\"field span2\">",
      "      <span>Address</span>",
      "      <textarea id=\"companyAddress\" rows=\"3\" placeholder=\"Unit 4, Example Way, Townsville, AB1 2CD\"></textarea>",
      "    </label>",
      "    <div class=\"field span2\" id=\"f-cqc\">",
      "      <label class=\"check-row\">",
      "        <input type=\"checkbox\" id=\"cqcRegistered\">",
      "        <span>CQC registered</span>",
      "      </label>",
      "      <small class=\"echo\">Tick if your organisation is registered with the Care Quality",
      "        Commission. The registration number is printed beside the company name.</small>",
      "    </div>",
      "    <label class=\"field span2\" id=\"f-cqcNumber\" hidden>",
      "      <span>CQC registration number <b>*</b></span>",
      "      <input type=\"text\" id=\"cqcNumber\" placeholder=\"e.g. 1-234567890\" autocomplete=\"off\">",
      "    </label>",
      "    <div class=\"field span2\" id=\"f-logo\">",
      "      <span>Company logo</span>",
      "      <div class=\"logo-row\">",
      "        <span class=\"logo-preview\" id=\"logoPreview\" hidden><img id=\"logoImg\" alt=\"\"></span>",
      "        <button type=\"button\" class=\"btn ghost small\" id=\"logoBtn\">Choose image&hellip;</button>",
      "        <button type=\"button\" class=\"btn ghost small\" id=\"logoRemove\" hidden>Remove</button>",
      "        <input type=\"file\" id=\"logoFile\" accept=\"image/png,image/jpeg\" hidden>",
      "      </div>",
      "      <small class=\"echo\" id=\"logoHint\">PNG or JPEG, printed at the top of the document.",
      "        Stored with this document and included when you export it.</small>",
      "    </div>",
      "  </div>",
      "</div>"
    ].join("\n"),

    quickadd: [
      "<div class=\"card\">",
      "  <h2>Quick add</h2>",
      "  <p class=\"hint\" id=\"quickHint\">Search the list to fill the form, then add the batch, expiry and quantity.",
      "    The suggested legal category is a starting point to save typing &mdash; check it against",
      "    your own policy and current legislation before the document is used.</p>",
      "  <div class=\"quick\">",
      "    <input type=\"search\" id=\"quickAdd\" autocomplete=\"off\" role=\"combobox\"",
      "           aria-expanded=\"false\" aria-controls=\"quickResults\"",
      "           placeholder=\"Search by name, formulation or strength&hellip;\">",
      "    <ul class=\"quick-results\" id=\"quickResults\" role=\"listbox\" hidden></ul>",
      "  </div>",
      "</div>"
    ].join("\n"),

    medform: [
      "<div class=\"card\">",
      "  <h2 id=\"medFormTitle\">Add medication</h2>",
      "  <form id=\"medForm\" novalidate>",
      "    <div class=\"grid\">",
      "      <label class=\"field span2\">",
      "        <span>Medication <b>*</b></span>",
      "        <input type=\"text\" id=\"mName\" placeholder=\"e.g. Paracetamol infant suspension\">",
      "      </label>",
      "      <label class=\"field span2\" id=\"f-mIndication\" hidden>",
      "        <span>Indication <b>*</b></span>",
      "        <textarea id=\"mIndication\" rows=\"3\"",
      "          placeholder=\"What it is given for. One per line for a list.\"></textarea>",
      "        <small class=\"echo\">Printed in the second column. Put each indication on its own",
      "          line and they are listed as bullets.</small>",
      "      </label>",
      "      <label class=\"field\">",
      "        <span>Presentation <b>*</b></span>",
      "        <input type=\"text\" id=\"mPresentation\" list=\"presentationList\" placeholder=\"e.g. Sachet\">",
      "        <datalist id=\"presentationList\">",
      "          <option value=\"Tablet\"><option value=\"Sachet\"><option value=\"Capsule\">",
      "          <option value=\"Dispersible tablet\"><option value=\"Instant melt tabs\">",
      "          <option value=\"Pre-filled syringe\"><option value=\"Ampoule\"><option value=\"Vial\">",
      "          <option value=\"Nebule\"><option value=\"Inhaler\"><option value=\"Suppository\">",
      "        </datalist>",
      "      </label>",
      "      <label class=\"field\">",
      "        <span>Dose / strength <b>*</b></span>",
      "        <input type=\"text\" id=\"mDose\" placeholder=\"e.g. 120mg/5ml\">",
      "      </label>",
      "      <label class=\"field\" id=\"f-mBatch\">",
      "        <span>Batch number</span>",
      "        <input type=\"text\" id=\"mBatch\" placeholder=\"e.g. X2257R\">",
      "      </label>",
      "      <div class=\"field\" id=\"f-mExpiry\">",
      "        <span>Expiry <b>*</b></span>",
      "        <div class=\"expiry-row\">",
      "          <select id=\"mExpiryPrecision\" aria-label=\"Expiry precision\">",
      "            <option value=\"month\">Month</option>",
      "            <option value=\"day\">Exact date</option>",
      "          </select>",
      "          <input type=\"month\" id=\"mExpiryMonth\" aria-label=\"Expiry month\">",
      "          <input type=\"date\" id=\"mExpiryDate\" aria-label=\"Expiry date\" hidden>",
      "          <input type=\"text\" id=\"mExpiryText\" hidden autocomplete=\"off\"",
      "                 placeholder=\"e.g. 07/25, 10/2027 or 18/10/2025\">",
      "        </div>",
      "        <small class=\"echo\" id=\"mExpiryEcho\">Most packs state a month, which runs to the last",
      "          day of that month. Switch to an exact date where the pack gives one.</small>",
      "      </div>",
      "      <label class=\"field\" id=\"f-mDoses\">",
      "        <span>Number of doses <b>*</b></span>",
      "        <input type=\"number\" id=\"mDoses\" min=\"1\" max=\"200\" step=\"1\" placeholder=\"e.g. 12\">",
      "      </label>",
      "      <label class=\"field\" id=\"f-mUnit\" hidden>",
      "        <span>Unit <b>*</b></span>",
      "        <input type=\"text\" id=\"mUnit\" list=\"unitList\" placeholder=\"e.g. ampoules\" autocomplete=\"off\">",
      "        <datalist id=\"unitList\">",
      "          <option value=\"ampoules\"><option value=\"vials\"><option value=\"tablets\">",
      "          <option value=\"capsules\"><option value=\"syringes\"><option value=\"tubes\">",
      "          <option value=\"patches\"><option value=\"ml\"><option value=\"mg\">",
      "        </datalist>",
      "        <small class=\"echo\">Printed on the register so the balance column is unambiguous.</small>",
      "      </label>",
      "      <label class=\"field\" id=\"f-mSchedule\">",
      "        <span>Schedule</span>",
      "        <select id=\"mSchedule\">",
      "          <option value=\"GSL\">GSL — General sales list</option>",
      "          <option value=\"P\">P — Pharmacy only</option>",
      "          <option value=\"POM\">POM — Prescription only</option>",
      "          <option value=\"S17\">S17 — Paramedic exemption (HMR Sch 17)</option>",
      "          <option value=\"S19\">S19 — Emergency parenteral (HMR Sch 19)</option>",
      "        </select>",
      "      </label>",
      "    </div>",
      "    <p class=\"notice info\" id=\"medNote\" hidden></p>",
      "    <p class=\"error\" id=\"medError\" hidden></p>",
      "    <div class=\"actions\">",
      "      <button type=\"submit\" class=\"btn primary\" id=\"medSubmit\">Add medication</button>",
      "      <button type=\"button\" class=\"btn ghost\" id=\"medCancel\" hidden>Cancel edit</button>",
      "    </div>",
      "  </form>",
      "</div>"
    ].join("\n"),

    medlist: [
      "<div class=\"card\">",
      "  <h2><span id=\"contentsTitle\">Bag contents</span> <span class=\"pill\" id=\"medCount2\">0</span></h2>",
      "  <div id=\"medList\" class=\"med-list\"></div>",
      "  <p class=\"empty\" id=\"medEmpty\">No medications added yet. Add the first one above.</p>",
      "</div>"
    ].join("\n"),

    generate: [
      "<div class=\"card\">",
      "  <h2>Generate document</h2>",
      "  <p class=\"hint\" id=\"generateHint\">A4 PDF: page 1 is the bag label, followed by one usage log per medication.</p>",
      "  <div id=\"summary\" class=\"summary\"></div>",
      "  <p class=\"notice\" id=\"expiryWarning\" hidden></p>",
      "  <p class=\"error\" id=\"genError\" hidden></p>",
      "  <div class=\"actions\">",
      "    <button type=\"button\" class=\"btn primary big\" id=\"generateBtn\">Download PDF</button>",
      "    <button type=\"button\" class=\"btn ghost\" id=\"previewBtn\">Preview in new tab</button>",
      "  </div>",
      "  <div class=\"notice reminder\" id=\"pdfReminder\" hidden>",
      "    <span id=\"pdfReminderText\"></span>",
      "    <button type=\"button\" class=\"btn ghost small\" id=\"pdfReminderExport\">Export .json now</button>",
      "  </div>",
      "</div>"
    ].join("\n"),

    saveload: [
      "<div class=\"card\">",
      "  <h2 id=\"saveTitle\">Save / load bag</h2>",
      "  <p class=\"hint\" id=\"saveHint\">Everything stays on this device — nothing is uploaded. Export a bag to reuse it next time.</p>",
      "  <p class=\"notice\" id=\"backupWarning\" hidden></p>",
      "  <div class=\"actions\">",
      "    <button type=\"button\" class=\"btn ghost\" id=\"exportBtn\">Export (.json)</button>",
      "    <button type=\"button\" class=\"btn ghost\" id=\"importBtn\">Import (.json)</button>",
      "    <input type=\"file\" id=\"importFile\" accept=\"application/json,.json\" hidden>",
      "  </div>",
      "</div>"
    ].join("\n"),

    footer: [
      "<p class=\"foot-line\">",
      "  <strong>Provided as is, with no warranty.</strong> This tool formats what you type &mdash; it",
      "  does not check it. You are responsible for verifying every entry, and every legal category,",
      "  before a document is used.",
      "</p>",
      "<details class=\"foot-details\">",
      "  <summary>Disclaimer, licence and sources</summary>",
      "  <div class=\"foot-body\">",
      "    <h3>Disclaimer</h3>",
      "    <p>Drug Bag Tracker is a document generator, not a clinical, pharmaceutical or legal",
      "      reference. Before any document is used, check that every entry matches the stock actually",
      "      held: name, formulation, strength, batch number, expiry, quantity and legal category.</p>",
      "    <p>The categories offered (GSL, P, POM, S17, S19, CD), including those pre-filled by the",
      "      quick-add list, are <strong>suggestions to save typing, not legal determinations</strong>.",
      "      Medicines can sit in more than one category depending on indication, route and pack size;",
      "      legislation is amended over time and this list is a fixed snapshot; and the categories were",
      "      not verified against primary legislation when the list was compiled. Check them against",
      "      current legislation and your own medicines policy, patient group directions and standard",
      "      operating procedures.</p>",
      "    <p>The controlled drugs register produced here is a convenience format. It does not",
      "      constitute, replace or discharge any statutory record-keeping duty. Satisfy yourself that",
      "      it meets the requirements that apply to you before relying on it.</p>",
      "    <p>Everything is stored in this browser and nothing is uploaded. Browser storage is not a",
      "      backup &mdash; export your documents to JSON and keep those files somewhere durable. No",
      "      responsibility is accepted for work lost to browser storage being cleared.</p>",
      "",
      "    <h3>Licence</h3>",
      "    <p>MIT licence. Copyright &copy; 2026 Finlay Russell. The software is provided &ldquo;as",
      "      is&rdquo;, without warranty of any kind, express or implied, including but not limited to",
      "      the warranties of merchantability, fitness for a particular purpose and non-infringement.",
      "      In no event shall the author be liable for any claim, damages or other liability arising",
      "      from, out of or in connection with the software or its use.</p>",
      "    <p>PDF generation uses <a href=\"https://github.com/parallax/jsPDF\" rel=\"noopener\"",
      "      target=\"_blank\">jsPDF</a>, bundled under the MIT licence.</p>",
      "",
      "    <h3>Sources</h3>",
      "    <p>The medication list is a user-supplied list of common pre-hospital medicines. The legal",
      "      category suggestions were informed by the Journal of Paramedic Practice article",
      "      <em>Paramedics and medicines: legal considerations</em>, NHS Specialist Pharmacy Service",
      "      guidance on legal mechanisms to supply and administer medicines, HCPC guidance on sale,",
      "      supply and administration, and Schedules 17 and 19 of the Human Medicines Regulations",
      "      2012. None of these is a substitute for the legislation itself, and the primary text was",
      "      not reachable when the list was compiled, so the categories are unverified against it.</p>",
      "  </div>",
      "</details>",
      "<p class=\"foot-credit\">",
      "  Made by Finlay Russell &mdash;",
      "  <a href=\"mailto:finlay3110@gmail.com\">finlay3110@gmail.com</a><br>",
      "  Runs entirely in your browser &middot; PDF by jsPDF",
      "</p>"
    ].join("\n")
  };

  /* Fills every [data-part] placeholder. Runs on load, before app.js wires
     anything up, so the rest of the app sees one complete document. */
  function render(root) {
    (root || document).querySelectorAll("[data-part]").forEach(function (el) {
      var html = PARTS[el.dataset.part];
      if (html === undefined) throw new Error("Unknown part: " + el.dataset.part);
      el.innerHTML = html;
    });
  }

  global.DBTParts = { parts: PARTS, render: render };
  render();
})(window);
